.github/workflows/actions.yml
README.md
azure-pipelines.yml
samples/HelloForms.Android/HelloForms.Android.csproj
samples/HelloForms.Android/appcenter-pre-build.sh
samples/HelloForms.iOS/HelloForms.iOS.csproj
samples/HelloForms/HelloForms.csproj

We have 16.4 Preview URLs now.
Bump Mono to a slightly newer version as well.

Bump URLs for Mono & Xamarin

---

.github/workflows/actions.yml
Boots.Tests/Boots.Tests.csproj
Boots/Boots.csproj
README.md
azure-pipelines.yml
scripts/build-and-test.yaml

Context: https://github.com/jonathanpeppers/boots/issues/19
`DOTNET_SKIP_FIRST_TIME_EXPERIENCE` is no longer needed.

Build with .NET Core 3.0

---

.github/workflows/actions.yml
README.md
azure-pipelines.yml

Fixes: https://github.com/jonathanpeppers/boots/issues/19
We should be able to drop all the .NET Core 2.2 installs now?

Test boots 1.0.1

---

Boots.Core/Boots.Core.csproj
Boots.Core/Bootstrapper.cs
Boots.Core/Downloader.cs
Boots.Core/MacUrlResolver.cs
Boots.Core/Product.cs
Boots.Core/ReleaseChannel.cs
Boots.Core/UrlResolver.cs
Boots.Core/WindowsUrlResolver.cs
Boots.Tests/UrlResolverTests.cs
Boots/Boots.csproj
Boots/Program.cs
Cake.Boots/BootsAddin.cs
Cake.Boots/Cake.Boots.csproj
Cake.Boots/build.cake
Directory.Build.props
azure-pipelines.yml
scripts/build-and-test.yaml

This enables commands such as:
boots --stable Xamarin.Android
boots --stable Xamarin.iOS
boots --preview Xamarin.Mac
boots --preview Mono
Or in a `cake` script:
```csharp
await Boots (Product.Mono);
await Boots (Product.XamariniOS);
await Boots (Product.XamarinAndroid, ReleaseChannel.Stable);
await Boots (Product.XamarinMac, ReleaseChannel.Preview);
```
These commands are possible by using the online manifests the VS updaters use.
Some examples of using the VS Windows manifests:
* https://github.com/dotnet/aspnetcore/blob/915cc74df832d40b270886b4d2d318d33d072404/eng/scripts/vs.json
* https://docs.microsoft.com/visualstudio/install/automated-installation-with-response-file
An open-source example of the VS Mac manifest:
* https://github.com/microsoft/workbooks/blob/1ef3b233398b03eec326cc4e8b …

New auto-resolving url feature

---

Cake.Boots/Cake.Boots.csproj

The latest builds are missing `Boots.Core.dll` and `System.Text.Json.dll`.
Added some MSBuild magic to fix this.

Fixes for Cake.Boots NuGet package

---

Boots.Core/PkgInstaller.cs
Boots.Tests/BootstrapperTests.cs
Cake.Boots/Cake.Boots.csproj
Cake.Boots/build.cake

I've gotten some reports of pkg files failing to install on macOS
Catalina, something like:
Querying https://software.xamarin.com/Service/Updates?v=2&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=0&pv4569c276-1397-4adb-9485-82a7696df22e=0&pvd1ec039f-f3db-468b-a508-896d7c382999=0&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=0&level=Stable
Downloading https://download.visualstudio.microsoft.com/download/pr/8f94ca38-039a-4c9f-a51a-a6cb33c76a8c/aa46188c5f7a2e0c6f2d4bd4dc261604/xamarin.android-10.2.0.100.pkg
Writing to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7kjmmg6c.nw4.pkg
Deleting /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7kjmmg6c.nw4.pkg
An error occurred when executing task 'provision-androidsdk'.
Error: One or more errors occurred. ('/usr/bin/sudo' with arguments '/usr/sbin/installer …

[macOS] add -dumplog switch to installer command

---

Boots.Core/AsyncProcess.cs
Boots.Core/Boots.Core.csproj
Boots.Core/Bootstrapper.cs
Boots.Core/Downloader.cs
Boots.Core/VsixInstaller.cs
Boots.Core/WindowsUrlResolver.cs
Boots/Boots.csproj
Boots/Program.cs
Cake.Boots/Cake.Boots.csproj

Context: https://docs.microsoft.com/dotnet/csharp/nullable-references
To properly setup NRT, I added:
<LangVersion>latest</LangVersion>
<Nullable>enable</Nullable>
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
As expected, this found one place that could possibly throw a `NullReferenceException`.
I also had to workaround one spot where `string.IsNullOrEmpty` does not have `[NotNullWhen(false)]` defined in netstandard2.0.

Setup nullable reference types

---

azure-pipelines.yml

Should fix:
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/15.0/bin/MSBuild.dll /nologo /bl:/Users/runner/work/1/s/bin/verify.binlog /p:Expected=10.4 /t:Check /v:minimal /Users/runner/work/1/s/scripts/xa-version.targets
XamarinAndroidVersion: 11.0.0-3
Expected: 10.4
/Users/runner/work/1/s/scripts/xa-version.targets(13,5): error : 11.0.0-3 did not match 10.4

[build] expect Xamarin.Android 11.0

---

Boots.Core/AsyncProcess.cs
Boots.Core/VsixInstaller.cs
Boots.Tests/AsyncProcessTests.cs
Boots.Tests/BootstrapperTests.cs
Boots.Tests/Utils.cs
scripts/build-and-test.yaml

Fixes: https://github.com/jonathanpeppers/boots/issues/42
If `VSIXInstaller.exe` returns a 1001 exit code, this means that the `.vsix` is already installed.
I think `boots` should just succeed in this case.
I also made some `CancellationToken` arguments in internal APIs non-optional. This will help not to forget them in the future.

[vsix] AlreadyInstalledException should complete successfully

---

Boots/Program.cs
README.md

Instead of `<stable>` and `<preview>`:
--stable <stable>      Install the latest *stable* version of a product from VS manifests. Options include: Xamarin.Android, Xamarin.iOS, Xamarin.Mac, and Mono.
--preview <preview>    Install the latest *preview* version of a product from VS manifests. Options include: Xamarin.Android, Xamarin.iOS, Xamarin.Mac, and Mono.
`boots` should print:
--stable <product>     Install the latest *stable* version of a product from VS manifests. Options include: Xamarin.Android, Xamarin.iOS, Xamarin.Mac, and Mono.
--preview <product>    Install the latest *preview* version of a product from VS manifests. Options include: Xamarin.Android, Xamarin.iOS, Xamarin.Mac, and Mono.

[boots] fix help text

---

Cake.Boots/BootsAddin.cs

Add attribute for Cake alias category which will list be used to list the aliases on the DSL reference page at https://cakebuild.net/dsl/ and on the addin detail page at https://cakebuild.net/extensions/cake-boots/

Add attribute for Cake alias category

---

.github/workflows/actions.yml

This way we aren't using `dotnet-install.sh` ourselves, it appears to
be failing now:
--2020-10-26 14:47:11--  https://dot.net/v1/dotnet-install.sh
Resolving dot.net (dot.net)... 40.113.200.201, 13.77.161.179, 104.215.148.63, ...
Connecting to dot.net (dot.net)|40.113.200.201|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh [following]
--2020-10-26 14:47:12--  https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh
Resolving dotnet.microsoft.com (dotnet.microsoft.com)... 13.107.246.10
Connecting to dotnet.microsoft.com (dotnet.microsoft.com)|13.107.246.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36458 (36K) …

[actions] use setup-dotnet

---

Boots.Core/Bootstrapper.cs
Boots.Core/FileType.cs
Boots.Core/Installer.cs
Boots.Core/MsiInstaller.cs
Boots.Core/PkgInstaller.cs
Boots.Core/VsixInstaller.cs
Boots.Tests/BootstrapperTests.cs
Boots.Tests/InstallerTests.cs
Boots/Program.cs
Cake.Boots/BootsAddin.cs
Cake.Boots/build.cake

Fixes: https://github.com/jonathanpeppers/boots/issues/31
This will help us in .NET 6 development.
We need to download and install .msi files as part of CI.

[msis] add new feature for .msi installers

---

Boots/Boots.csproj

Context: https://natemcmaster.com/blog/2019/01/09/netcore-primitives-3/
Context: https://github.com/dotnet/designs/blob/main/accepted/2019/runtime-binding.md#rollforward
Previously when running `boots` on a machine with *only* .NET 5.0 and
no .NET Core 3.1, you could hit:
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
To solve this, we need our `*.runtimeconfig.json` to allow things to
automatically roll forward to .NET 5.0 if .NET Core 3.1 is not found.
If we set `$(RollForward)` to `Major`:
> `Major` -- Roll forward to lowest higher major version, and lowest
> minor version, if requested major version is missing. If the
> requested major version is present, then the `Minor` policy is used.
I think this …

[build] use $(RollForward) Major instead of multi-targeting

---

Boots.Tests/Boots.Tests.csproj
Boots.Tests/MainTests.cs
Boots/Program.cs
nuget.config

I noticed this on CI:
> dotnet Boots/bin/$(Configuration)/netcoreapp3.1/Boots.dll --preview Xamarin.Android
At least one of --url, --stable, or --preview must be used
What? `--preview` was passed???
This broke in 674d09b6e, when I used the wrong API for validating
incoming command-line options...
I will delist 1.0.3.551.
To prevent this in the future, I added `MainTests` that actually check
that the `static Task Main()` returns the proper output and works
correctly.

Fix `boots` command-line arguments

---

Boots.Core/Bootstrapper.cs
Boots.Core/Downloader.cs
Boots.Core/MacUrlResolver.cs
Boots.Core/WindowsUrlResolver.cs
Boots.Tests/BootstrapperTests.cs
Boots/Program.cs

Might help: https://github.com/jonathanpeppers/boots/issues/61
* `--timeout` sets the `Timeout` property on all instances of `HttpClient`.
* Reworks `HttpClient` usage so all are created/disposed with `using`.
* Flattened a couple `using`-blocks and used `using var` instead.

Add --timeout switch

---

Boots.Core/Bootstrapper.cs
Boots.Tests/HttpClientWithPolicyTests.cs

Expanding upon 607adb08, boots should log something like this on retries:
Logger.WriteLine ($"Retry attempt {count}: {exc}")
So there is actual insight to what is happening!
Updated some tests to verify what happens when different exception types are thrown.

Add logging on retries

---

Boots/Boots.csproj
Cake.Boots/Cake.Boots.csproj
Directory.Build.targets
appveyor.yml
scripts/build-and-test.yaml

* Use $(GeneratePackageOnBuild), so we don't need `dotnet pack`
* Consolidate a few more settings in `Directory.Build.targets`

[build] consolidate NuGet packaging settings

---

.github/workflows/actions.yml

I think this is the same issue that happens on Azure DevOps, where we are trying to use Java 14 by default.

[gh actions] set $JI_JAVA_HOME

---

Boots/Boots.csproj
azure-pipelines.yml

The .NET 6 SDK doesn't support `netcoreapp2.1`, so dropping it.

[build] drop netcoreapp2.1 support

---

appveyor.yml

This avoids the missing .NET 6 install for the tests.
The macOS image has .NET 5 as the latest right now:
https://www.appveyor.com/docs/macos-images-software/

[appveyor] only build 1 project

---

Boots.Core/Bootstrapper.cs
Boots.Core/VsixInstaller.cs
Boots.Tests/BootstrapperTests.cs
Boots/Program.cs

Because we are sharing build agents with a process that is testing PR `.vsix` files, we often need to replace those PR builds with a stable lower version `.vsix`, which is not supported by `vsixinstaller.exe`.  Add the option `--downgrade-first`, which will first revert the installed package back to the version that ships with the VS version, so we may then upgrade it to our desired version.
Log file where downgrade was performed but not needed (error is written to log, but does not stop the process):
[no-downgrade-needed.txt](https://github.com/jonathanpeppers/boots/files/8327694/no-downgrade-needed.txt)
Log file where downgrade was needed (first installs higher version, then downgrades and installs desired version):
[downgrade-needed.txt](https://github.com/jonathanpeppers/boots/files/83 …

Add --downgrade-first option.

---

azure-pipelines.yml

We can't install the latest Xamarin.Android builds anymore in 2019, so I think we can just remove this lane now.
I don't think it's going to catch any bugs in `boots` to keep it anyway.

[build] remove VS 2019 job
